# Should be set in the environment:
TARGET_ARCH     = linux64
SYSTEMC_HOME    = /home/alpizape/systemc-2.3.0
#SYSTEMC_HOME    = /home/hora/systemc-2.3
#TLM_HOME        = /root/software/tlm-2008-06-09/

# setup SYSTEM_HOME and TARGET_ARCH in your environment
SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
#TLM_INC_DIR      = $(TLM_HOME)/include
#libdir = /home/alpizape/systemc-2.3.0/objdir/lib

GXX = g++
GCC = gcc
LD  = g++
FLAGS = -g -Werror -Wno-long-long -Wno-deprecated -I$(SYSTEMC_INC_DIR) 

#-I$(TLM_INC_DIR)

#LDFLAGS = -L$(SYSTEMC_LIB_DIR) -lsystemc -L$(SYSTEMC_LIB_DIR) -L$(SYSTEMC_LIB_DIR) -Wl,-rpath=$(SYSTEMC_LIB) -lsystemc
LDFLAGS = -L$(SYSTEMC_LIB_DIR) -Wl,-rpath=$(SYSTEMC_LIB_DIR) -lsystemc
#-lscv
